### PR TITLE
[GBDT] Bug fix & histogram subtraction

### PR DESCRIPTION
**Pull request by Morrissss**
Fix several boundary bugs. Maybe the beg-end naming convention usually implies left-close-right-open boundaries?

Add histogram subtraction to speed up histogram calculation (inspired by [LightGbm](https://github.com/Microsoft/LightGBM). The basic idea is if we already know the histogram one node and its parent's, its sibling's histogram can be simply calculated by subtraction.

Re-factoring that needs more help and discussion:
- I think in GBDT, each worker group only involves one core. We can not accelerate CPU-intensive process like histogram calculation by multi-threading.
- If I'm wrong, the lock-free `activeNodeStat[]` will face severe racing condition in multi-core environment, and should be replace by `AtomicInteger` or `CountDownLatch`
- So I move the CPU-intensive procedure from `GradHistThread` into `runActiveNode`, leave the IO-intensive part, and remove sample batching. To check whether it is right, benchmark needs to be re-run (histogram subtraction should be disable).

### CODE REVIEW

**Comment by paynie** [comment]
Thanks, we will review it

**Comment by bluesjjw** [comment]
To answer your questions.
- Recent GBDT systems generally use multi-threading to accelerate training. For example, XGBoost processes several data blocks in parallel. Our method, however, processes sibling tree nodes in parallel.
- You are right. AtomicInteger seems better.

Thanks for your contributions and suggestions.
Please keep in touch.

**Comment by Morrissss** [comment]
Thanks for review @bluesjjw . I will try to fix that during holiday.
One more question: does `ml.gbdt.thread.num` setting involve multiple core into one workergroup? Or, how to use multiple cores in one workergroup?

Thanks again. Great job!

**Comment by Morrissss** [comment]
[Here is the change](https://github.com/Tencent/angel/pull/326/commits/9f4674a46ea04c6b10d0f171ecfa0276fcb8f11f)

**Comment by bluesjjw** [comment]
Thanks a lot for your contribution!
Owing to the code conflict, we cannot directly merge your PR.
But, I have merged your code into our new version.

Thanks again!

**Comment by Morrissss** [comment]
@bluesjjw That's cool. Thank you.

**Pull request closed without merging**
