### PR TITLE
migrate kmeans from spark version into spark on angel

### PR DESCRIPTION
**Pull request by hbghhy**
I just migrate the kmeans of spark.ml into spark on angel like org.apache.spark.ml.classification.ps.LogisticRegression. Because the org.apache.spark.ml.clustering.kmeans in ml is like a wrapper of org.apache.spark.mllib.clustering. I have to copy and rewrite some code in the mllib into angel style. And not like the test of lr, I add some config code for angel of spark origin test so that I can test the code in local mode.
Since the angel is different from origin spark, please check my code when i use the psvector, especially the initKMeansParallel method in kmeans.
THX.

### CODE REVIEW

**Comment by ZunwenYou** [comment]
Great Work.
Can you present the performance comparison between Spark KMeans and Spark on Angel KMeans?

**Comment by hbghhy** [comment]
OK, I can try. Is there some util function or example to compare performance? Or I just use some time function to do a approximate comparison?

**Comment by ZunwenYou** [comment]
We do not have benchmark tools right now. 
You can use time function to record the whole application time cost.

**Comment by hbghhy** [comment]
I have test the performance of my new code, which is almost same with the spark version except the iteration to get new centers. And I get some interesting issue. I compare it by these code:
```

import com.tencent.angel.spark.PSContext
import org.apache.spark.SparkConf
import org.apache.spark.ml.clustering.ps.KMeans
import org.apache.spark.ml.linalg.{Vector, Vectors}
import org.apache.spark.sql.{DataFrame, Dataset, SparkSession}
import org.apache.spark.ml.clustering.{KMeans => MLKMeans}

import scala.util.Random

/**
  * Created by hanyuhuang on 2017/8/9.
  */
object KmeansTest {
  def time[R](block: => R): R = {
    val t0 = System.nanoTime()
    val result = block    // call-by-name
    val t1 = System.nanoTime()
    println("Elapsed time: " + (t1 - t0)/1000000 + "ms")
    println("Elapsed time: " + (t1 - t0).toDouble/1000000000 + "s")
    result
  }

  def main(args: Array[String]): Unit = {
    val conf = new SparkConf
    val master = conf.getOption("spark.master")
    val isLocalTest = if (master.isEmpty || master.get.toLowerCase.startsWith("local")) true else false
    val sparkBuilder = SparkSession.builder().appName("kmeans test")
    if (isLocalTest) {
      sparkBuilder.master("local[3]")
        .config("spark.ps.mode", "LOCAL")
        .config("spark.ps.jars", "")
        .config("spark.ps.instances", "1")
        .config("spark.ps.cores", "1")
    }
    val sc = sparkBuilder.getOrCreate().sparkContext
    sc.setLogLevel("INFO")

    val k=5000
    val dataset=KMeansSuite.generateSparseData(sparkBuilder.getOrCreate(),5000000,50,k).cache()
    dataset.first()
    println("spark performance:")
    time({
      val predictionColName = "kmeans_prediction"
      val kmeans = new MLKMeans().setK(k).setPredictionCol(predictionColName).setSeed(1)
      val model = kmeans.fit(dataset)
      //assert(model.clusterCenters.length === k)

      val transformed = model.transform(dataset)
      transformed.show(false)
      println(model.computeCost(dataset))
      model.clusterCenters.foreach(println(_))
    })
    println("angel performance:")
    time({
      val predictionColName = "kmeans_prediction"
      val kmeans = new KMeans().setK(k).setPredictionCol(predictionColName).setSeed(1)
      val model = kmeans.fit(dataset)
      //assert(model.clusterCenters.length === k)

      val transformed = model.transform(dataset)
      transformed.show(false)
      println(model.computeCost(dataset))
      model.clusterCenters.foreach(println(_))
    })
    PSContext.stop()
    sc.stop()
  }
}

case class TestRow(features: Vector)
object KMeansSuite {
  def generateKMeansData(spark: SparkSession, rows: Int, dim: Int, k: Int): DataFrame = {
    val sc = spark.sparkContext
    val rdd = sc.parallelize(1 to rows).map(i => Vectors.dense(Array.fill(dim)((i % k).toDouble)))
      .map(v => new TestRow(v))
    spark.createDataFrame(rdd)
  }

  def generateSparseData(spark: SparkSession, rows: Int, dim: Int, seed: Int): DataFrame = {
    val sc = spark.sparkContext
    val random = new Random(seed)
    val nnz = random.nextInt(dim)
    val rdd = sc.parallelize(1 to rows)
      .map(i => Vectors.sparse(dim, random.shuffle(0 to dim - 1).slice(0, nnz).sorted.toArray,
        Array.fill(nnz)(random.nextDouble())))
      .map(v => new TestRow(v))
    spark.createDataFrame(rdd)
  }
}
```
Firstly, when I run the code in a local mode with a small dataset, the spark on angel version is slower than the origin spark. Like following:

spark performance:
Elapsed time: 6204ms
Elapsed time: 6.204453615s
angel performance:
Elapsed time: 51324ms
Elapsed time: 51.324951489s

There are two main time cost of my code:
1.INFO KMeans: Initialization context with kmeans_408bf97a8359__initMode took 21.935 seconds.(This is the time: PSContext.getOrCreate.createModelPool(featureNum, $(k)) took.)

2.My code take much more time at the iteration of kmeans:
spark:
17/08/09 16:45:06 INFO KMeans: Iterations took 3.411 seconds.
17/08/09 16:45:06 INFO KMeans: KMeans reached the max number of iterations: 20.
spark on angel:
17/08/09 16:45:57 INFO KMeans: Iterations took 23.616 seconds.
17/08/09 16:45:57 INFO KMeans: KMeans reached the max number of iterations: 20.

In my opinion, when I run the code in a local mode, the angel mode will get less cpu than spark(It need a ps?). Or the advantage of ps can be seen when you create a large dataset with many clusters and features, then the pull and push may be faster than broadcast. Since my cluster will crash every time they create ps, I cannot test a large dataset, maybe you can try. And maybe the code of my iteration has some bug?(the code is at the 297 line of KMeans.scala).
THX

**Comment by ZunwenYou** [comment]
Do you have a bigger yarn cluster? local mode is designed for local debugging.
We can try this in yarn cluster with more data.

**Comment by hbghhy** [comment]
I used to try to run a large dataset with 100 excutors and 10 ps. The spark part played well, but when it came to angel part, the cluster got stuck in new ps. (In the web UI, the 10 ps just stuck in new state and never turn into running.) It seems to be a deploy problem of our cluster. So maybe I will try it when it is deploy in a right way.

**Comment by ZunwenYou** [comment]
Maybe you can present the PS log here.

**Comment by hbghhy** [comment]
The spark part play well:
```
spark performance:
Elapsed time: 309788ms
Elapsed time: 309.788576239s
```
Here is some error log:
```
17/08/10 09:50:14 INFO DAGScheduler: Job 37 finished: countByValue at KMeans.scala:241, took 115.432085 s
17/08/10 09:50:14 INFO TorrentBroadcast: Destroying Broadcast(84) (from destroy at KMeans.scala:243)
17/08/10 09:50:14 INFO BlockManagerInfo: Removed broadcast_84_piece0 on 100.76.10.204:47948 in memory (size: 39.7 KB, free: 3.3 GB)
17/08/10 09:50:14 INFO BlockManagerInfo: Removed broadcast_84_piece0 on 100.76.75.78:60718 in memory (size: 39.7 KB, free: 284.3 MB)
17/08/10 09:50:14 INFO BlockManagerInfo: Removed broadcast_84_piece0 on 100.76.75.78:38902 in memory (size: 39.7 KB, free: 284.3 MB)
17/08/10 09:50:14 INFO LocalKMeans: Local KMeans++ converged in 3 iterations.
17/08/10 09:50:14 ERROR MatrixTransportClient: updater fatal error happened updater request failed com.tencent.angel.ml.matrix.psf.update.primitive.Push
17/08/10 09:50:14 INFO PSAgent: psagent falied
17/08/10 09:50:14 INFO PSAgent: stop heartbeat thread!
17/08/10 09:50:14 INFO PSAgent: stop op log merger
17/08/10 09:50:14 WARN MatrixOpLogCache: oplog-merge-dispatcher interrupted
17/08/10 09:50:14 INFO PSAgent: stop clock cache
17/08/10 09:50:14 INFO PSAgent: stop matrix cache
17/08/10 09:50:14 INFO PSAgent: stop matrix client adapater
17/08/10 09:50:14 INFO PSAgent: stop rpc dispacher
17/08/10 09:50:14 INFO ClockCache: sync thread is interupted
17/08/10 09:50:14 INFO MatrixClientAdapter: interupted
17/08/10 09:50:14 WARN MatrixTransportClient: RequestDispacher exit as interrupt

```
and here:
```
17/08/10 09:47:14 ERROR ResourceLeakDetector: LEAK: ByteBuf.release() was not called before it's garbage-collected. Enable advanced leak reporting to find out where the leak occurred. To enable advanced leak reporting, specify the JVM option '-Dio.netty.leakDetection.level=advanced' or call ResourceLeakDetector.setLevel() See http://netty.io/wiki/reference-counted-objects.html for more information.
17/08/10 09:50:14 ERROR MatrixTransportClient: updater fatal error happened updater request failed com.tencent.angel.ml.matrix.psf.update.primitive.Push
```

**Comment by ZunwenYou** [comment]
Exception is throw when  `centers(j).vector.toRemote.push(newCenter.vector.toArray)` is executed.
It means PS nodes have started successfully, 
`val psPool = PSContext.getOrCreate.createModelPool(featureNum, $(k))`

**Comment by hbghhy** [comment]
Yes, but is it normal? Since it run well in a local mode. It is a bug of code or a cluster issue?

**Comment by ZunwenYou** [comment]
can you find log about why pull is failed?
I do not know why pull failed.
have you succeed with example case in your Cluster？

**Comment by hbghhy** [comment]
I used to run the example in cluster succeed weeks ago. But I guess the config of our cluster has some error. Just like I said.  I ran the same code yesterday, the ps context cannot initial. It seems to throw a io exception about connection today. And another time the log I have put. I will try when I confirm the cluster is settled. Maybe you can close this PR first. And I will pull again when I confirm our cluster is fine and finish the test.THX

**Comment by andyyehoo** [comment]
Thanks for your contribution of this algorithm. It seems not to be a problem of your code.

So we will accept this first.  And we will also do more test on it. Please also go on with your confirm work. (If you don't mind, u can send more details about your cluster to us privately. This may help.)

**Comment by hbghhy** [comment]
THX. I used to test it on tesla. Hah... But I will left company recently and go back school, so I may not have the resource to test it. And I will try implement some algorithm on the angel-ps when I have time and do more test next time.  THX again, especially @ZunwenYou

**Pull request merged**
